Feature/#131 created notificaiton sender services
sulton-max/Training.TruckWorld.Clone pull request #142
Opened 2023-11-21 22:35 UTC by Ozodbek4

2023-11-22 05:40 UTC, sulton-max requested changes

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Validators/EmailMessageValidator.cs
> +                RuleFor(message => message.Variables).NotNull();
So the first check must be template right ?

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/SmsSenderService.cs
> +    public SmsSenderService(IEnumerable<ISmsSenderBroker> smsSenderBroker, IValidator<SmsMessage> smsSenderValidator)
Use primary constructor

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Validators/SmsMessageValidator.cs
> +                RuleFor(message => message.RecieverPhoneNumber).NotNull().NotEmpty();
Check with regex from external validation ( inject `ValidationSettings` into validator )

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Validators/EmailMessageValidator.cs
> +                RuleFor(message => message.SenderEmailAddress).NotNull().NotEmpty();
Check with regex from external validation ( inject `ValidationSettings` into validator )

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailSenderService.cs
> +    public EmailSenderService(IEnumerable<IEmailSenderBroker> emailSenderBrokers, IValidator<EmailMessage> validator)
Use primary constructor

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Brokers/TwilioSmsSenderBroker.cs
> +    public TwilioSmsSenderBroker(IOptions<TwilioSmsSenderSettings> settings) =>
Use primary constructor

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Brokers/SmtpEmailSenderBroker.cs
> +        mail.IsBodyHtml = true;
Actually add this to email template and set from email template

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Brokers/SmtpEmailSenderBroker.cs
> +        _settings = smtpEmailSenderSettings.Value;
Use primary constructor

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Mapper/NotificationMessageMapper.cs
> +public class NotificationMessageMapper : Profile
Is it supposed to map from notification message to sms message and email message ?

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Enums/NotificationEvent.cs
> +    OnRedering,
Fix to OnRendering

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Entities/SmsTemplate.cs
> +public class SmsTemplate : IEntity
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Entities/EmailTemplate.cs
> +public class EmailTemplate : IEntity
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Services/ISmsSenderService.cs
> +public interface ISmsSenderService
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Services/IEmailSenderService.cs
> +public interface IEmailSenderService
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Models/SmsMessage.cs
> +public class SmsMessage : NotificationMessage
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Models/NotificationMessage.cs
> +public class NotificationMessage
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Models/EmailMessage.cs
> +public class EmailMessage : NotificationMessage
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Brokers/ISmsSenderBroker.cs
> +public interface ISmsSenderBroker
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Brokers/IEmailSenderBroker.cs
> +public interface IEmailSenderBroker
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Settings/SmtpEmailSenderSettings.cs
> +public class SmtpEmailSenderSettings
Add docs

2023-11-22 05:40 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Settings/TwilioSmsSenderSettings.cs
> +public class TwilioSmsSenderSettings
Add docs

2023-11-23 15:01 UTC, Ozodbek4 commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailSenderService.cs
> +    public EmailSenderService(IEnumerable<IEmailSenderBroker> emailSenderBrokers, IValidator<EmailMessage> validator)
project in .Net 7

2023-11-23 19:04 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Brokers/TwilioSmsSenderBroker.cs
> +namespace TruckWorld.Infrastructure.Common.Notifications.Brokers;
Remove unnecessary row

2023-11-23 19:04 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailSenderService.cs
> +
Use .NET 8 Primary constructor

2023-11-24 06:26 UTC, closed without merging