Feature/#130
sulton-max/Training.TruckWorld.Clone pull request #144
Opened 2023-11-23 15:08 UTC by Mirzohid-Mominov

Created services and models for Notification

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Configurations/HostConfiguration.Extensions.cs
> +
remove unnecessary rows

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Configurations/HostConfiguration.cs
>              .AddDevTools()
Add first AddPersistence

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Controllers/NotificationsController.cs
> +
change Primary constructor

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Program.cs
> +
remove unnecessary row

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Program.cs
> +
remove unnecessary row

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/TruckWorld.Api.csproj
remove unnecessary row

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Entities/EmailTemplate.cs
> +namespace TruckWorld.Domain.Entities;
remove unnecessary rows

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Entities/NotificationTemplate.cs
> +}
you should write docs in each property

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Entities/SmsTemplate.cs
> +    public SmsTemplate()
in mentioned above, write docs

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Enums/NotificationType.cs
> +    public enum NotificationType
write docs

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailTemplateService.cs
> +public class EmailTemplateService : IEmailTemplateService
should be one row in each class or method . In here , should be row after namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailTemplateService.cs
> +    public IQueryable<EmailTemplate> Get(Expression<Func<EmailTemplate, bool>>? predicate = default,
remove unnecessary row

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailTemplateService.cs
> +
'=> _emailTemplateRepository.Get(predicate, asNoTracking);'

i think , this version is good bro )

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Entities/EmailTemplate.cs
> +public class EmailTemplate : NotificationTemplate
remove row between docs and class

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/SmsTemplateService.cs
> +}
remove unnecessary row

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Validators/EmailTemplateValidator.cs
> +        }
add email min,max length

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/EntityConfigurations/NotificationTemplateConfiguration.cs
> +    public class NotificationTemplateConfiguration : IEntityTypeConfiguration<NotificationTemplate>
it is better  to use "  ; " , instead of using this  "{ }" in namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/EntityConfigurations/SmsTemplateConfiguration.cs
> +    public class SmsTemplateConfiguration : IEntityTypeConfiguration<SmsTemplate>
use " ; " instead of " { } " in namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/EntityConfigurations/SmsTemplateConfiguration.cs
> +        }
Configure method should be empty?

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Migrations/20231123064322_AddMigration.cs
> +    /// <inheritdoc />
bro, edit namespace ( " { } ").

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Migrations/20231123065315_AddMigrations.cs
> +    /// <inheritdoc />
edit namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Migrations/NotificationsDbContextModelSnapshot.cs
> +    [DbContext(typeof(NotificationsDbContext))]
in mentioned above, edite namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Repositories/EmailTemplateRepository.cs
> +    public class EmailTemplateRepository : EntityRepositoryBase<EmailTemplate, NotificationsDbContext>, IEmailTemplateRepository
edit namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Repositories/EmailTemplateRepository.cs
> +        IQueryable<EmailTemplate> IEmailTemplateRepository.Get(
remove unnecessary rows

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Repositories/Interfaces/IEmailTemplateRepository.cs
> +    public interface IEmailTemplateRepository
edit namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Repositories/Interfaces/ISmsTemplateRepository.cs
> +    public interface ISmsTemplateRepository
edit namespace

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Repositories/SmsTemplateRepository.cs
> +        IQueryable<SmsTemplate> ISmsTemplateRepository.Get(
remove unnecessary rows

2023-11-23 16:51 UTC, botirjonabdumannonovv commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Repositories/SmsTemplateRepository.cs
> +    }
remove unnecessary rows

2023-11-26 15:31 UTC, Habiba67y commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Controllers/NotificationsController.cs
> +    [HttpGet("getSmsTemplates")]
"getSmsTemplates" emas "templates/sms" qilib yozish kerak,
 + "templates" deb ham sms ham email template larni ham get qiladigan method qilgan yaxshi manimcha

2023-11-26 15:31 UTC, Habiba67y commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Api/Controllers/NotificationsController.cs
> +    [HttpGet("getEmailTemplates")]
bu yerda ham, "templates/email"

2023-11-26 15:31 UTC, Habiba67y commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Application/Common/Notifications/Services/IEmailTemplateService.cs
> +    ValueTask<EmailTemplate?> GetBytypeAsync(
GetByTypeAsync, not GetBytypeAsync

2023-11-26 15:31 UTC, Habiba67y commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Enums/NotificationTemplateType.cs
> +        Welcomenotification = 0,
WelcomeNotification

2023-11-26 15:31 UTC, Habiba67y commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Domain/Enums/NotificationTemplateType.cs
> +        PhoneNumberVerificationnotification = 2,
PhoneNumberVerificationNotification bo'miydimi?

2023-11-28 08:16 UTC, Abdurahmon0412 requested changes

2023-11-28 08:16 UTC, Abdurahmon0412 commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Infrastructure/Common/Notifications/Services/EmailTemplateService.cs
> +            .SingleOrDefaultAsync(cancellationToken);
mana shu yerida logikada xato ketibdi templatetype = template typeligi aniqku o'zi 
xuddi 5 == 5 deb tekshirgandek bo'lib qolibdi

2023-11-28 08:50 UTC, closed without merging