Feature/#130
sulton-max/Training.TruckWorld.Clone pull request #146
Opened 2023-11-30 07:20 UTC by Mirzohid-Mominov

2023-12-14 13:37 UTC, sulton-max requested changes

2023-12-14 13:37 UTC, sulton-max commented on src/Training.TruckWorld.Clone.Backend/TruckWorld.Persistence/Migrations/20231128100406_AddEmailTemplate.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
why migrations are empty ?

2023-12-21 14:25 UTC, sulton-max approved these changes
Looks good

2023-12-25 14:41 UTC, Habiba67y approved these changes

2023-12-25 14:42 UTC, merged